schema: workflow/2022.04
name: Scheduler
inactive: true
settings:
  error_notification: true
  network: net_5Lnie3
triggers:
- id: hi_BpHkPLe
- id: ti_0yTPezK
steps:
- namespace: braze_get_scheduled_messages
  runtime: nodejs20.x
  uses: "./braze_get_scheduled_messages/entry.js"
  props:
    braze:
      authProvisionId: apn_0WhgpWJ
    endTime: "{{new Date(Date.now() + 24*60*60*1000).toISOString()}}"
- namespace: utils_filter_by_tags
  runtime: nodejs20.x
  uses: "@mcclatchy/utils-filter-by-tags@0.0.2"
  props:
    items: "{{steps.braze_get_scheduled_messages.$return_value}}"
    targetTags:
    - Proof
- namespace: code
  disabled: true
  runtime: nodejs20.x
  uses: "./code/entry.js"
  props:
    items: "{{steps.utils_filter_by_tags.$return_value}}"
    workflowUrl: https://eone5ahulwjwhb6.m.pipedream.net
- namespace: load_newsletter_routes
  runtime: nodejs20.x
  uses: snowflake-execute-sql-query@0.2.3
  props:
    snowflake:
      authProvisionId: apn_yghdQYJ
    sql:
      value: |-
        SELECT NEWSLETTER_KEY, PROOF_WORKFLOW_URL
        FROM MCC_RAW.MARKETING_DEV.NEWSLETTER_CONFIG
        WHERE ENABLED = TRUE AND PROOF_WORKFLOW_URL IS NOT NULL
      query: |-
        SELECT NEWSLETTER_KEY, PROOF_WORKFLOW_URL
        FROM MCC_RAW.MARKETING_DEV.NEWSLETTER_CONFIG
        WHERE ENABLED = TRUE AND PROOF_WORKFLOW_URL IS NOT NULL
- namespace: route_and_trigger
  runtime: nodejs20.x
  uses: "./route_and_trigger/entry.js"
  props:
    items: "{{steps.utils_filter_by_tags.$return_value}}"
- namespace: create_folder
  disabled: true
  runtime: nodejs20.x
  uses: google_drive-create-folder@0.1.16
  props:
    name: "{{steps.trigger.event.timezone_configured.iso8601.date}}"
    createIfUnique: true

