schema: workflow/2022.04
name: Scheduler
inactive: true
settings:
  error_notification: true
  network: net_5Lnie3
triggers:
- id: hi_BpHkPLe
steps:
- namespace: utils_filter_by_tags
  runtime: nodejs20.x
  uses: "@mcclatchy/utils-filter-by-tags@0.0.2"
  props:
    items: "{{steps.braze_get_scheduled_messages.$return_value}}"
    targetTags:
    - Proof
- namespace: code
  runtime: nodejs20.x
  uses: "./code/entry.js"
  props:
    items: "{{steps.utils_filter_by_tags.$return_value}}"
    workflowUrl: https://eou1vpj5be9iob8.m.pipedream.net
- namespace: route_and_trigger
  disabled: true
  runtime: nodejs20.x
  uses: "./route_and_trigger/entry.js"
- namespace: create_folder
  disabled: true
  runtime: nodejs20.x
  uses: google_drive-create-folder@0.1.16
  props:
    googleDrive:
      authProvisionId: apn_mnh5B9x
    name: "{{steps.trigger.event.timezone_configured.iso8601.date}}"
    createIfUnique: true

