schema: workflow/2022.04
name: Email Test API
settings:
  error_notification: true
  network: net_5Lnie3
triggers:
- id: hi_a1HnwvK
steps:
- namespace: validate_and_respond
  runtime: nodejs20.x
  uses: "./validate_and_respond/entry.js"
- namespace: eoa_create_test
  runtime: nodejs20.x
  uses: "./eoa_create_test/entry.js"
- namespace: eoa_poll_results
  runtime: nodejs20.x
  uses: "./eoa_poll_results/entry.js"
- namespace: post_to_callback
  runtime: nodejs20.x
  uses: "./post_to_callback/entry.js"
