schema: workflow/2022.04
name: Email Test API
settings:
  error_notification: true
  network: net_5Lnie3
triggers:
- id: hi_a1HnwvK
steps:
- namespace: validate_and_respond
  runtime: nodejs20.x
  uses: "./validate_and_respond/entry.js"
  props:
    default_external_user_ids:
    - ad0e2d4700023d3462ac8a72ca9c7dfc2621bbcf83f8ffddd4f963e7c92488bb
    braze_app_id: MCC
- namespace: braze_send
  runtime: nodejs20.x
  uses: "./braze_send/entry.js"
  props:
    braze:
      authProvisionId: apn_0WhgpWJ
    payload: "{{steps.validate_and_respond.$return_value.braze_payload}}"
- namespace: wait_for_eoa
  runtime: nodejs20.x
  uses: delay-workflow-delay@0.0.2
  props:
    delayDurationValue: 10
    delayDurationUnit: Minutes
- namespace: eoa_find_test
  runtime: nodejs20.x
  uses: "./eoa_find_test/entry.js"
  props:
    email_on_acid:
      authProvisionId: apn_b6hZOVx
    subject: "{{steps.validate_and_respond.$return_value.subject}}"
- namespace: eoa_get_results
  runtime: nodejs20.x
  uses: "./eoa_get_results/entry.js"
  props:
    email_on_acid:
      authProvisionId: apn_b6hZOVx
    testId: "{{steps.eoa_find_test.$return_value.testId}}"
    clientKeys: "{{steps.validate_and_respond.$return_value.client_keys}}"
- namespace: post_to_callback
  runtime: nodejs20.x
  uses: "./post_to_callback/entry.js"
  props:
    callback_url: "{{steps.validate_and_respond.$return_value.callback_url}}"
    subject: "{{steps.validate_and_respond.$return_value.subject}}"
    testId: "{{steps.eoa_find_test.$return_value.testId}}"
    screenshots: "{{steps.eoa_get_results.$return_value.screenshots}}"
    fullResults: "{{steps.eoa_get_results.$return_value.fullResults}}"

