schema: workflow/2022.04
name: Slack Reply with Proof
inactive: true
settings:
  error_notification: true
triggers:
- id: dc_DvuwbaM
steps:
- namespace: filter
  runtime: nodejs20.x
  uses: "./filter/entry.js"
  props:
    _filter:
      continue: 'true'
      rules:
        t: and
        r:
        - a: "{{steps.trigger.event.text}}"
          op: str/
          b: Proof
        - a: "{{steps.trigger.event.bot_profile.name}}"
          op: str=
          b: Pipedream
- namespace: details
  runtime: nodejs20.x
  uses: "./details/entry.js"
- namespace: get_folder_id_for_path
  runtime: nodejs20.x
  uses: google_drive-get-folder-id-for-path@0.1.17
  props:
    googleDrive:
      authProvisionId: apn_mnh5B9x
    path: "{{steps.details.$return_value.date}}/{{steps.details.$return_value.communication}}"
- namespace: list_files
  runtime: nodejs20.x
  uses: google_drive-list-files@0.1.19
  props:
    googleDrive:
      authProvisionId: apn_mnh5B9x
- namespace: code
  runtime: nodejs20.x
  uses: "./code/entry.js"
- namespace: reply_to_a_message_preview
  disabled: true
  runtime: nodejs20.x
  uses: slack_v2-reply-to-a-message@0.2.0
  props:
    text: "{{steps.code.$return_value.preview}}"
    as_user: false
    addToChannel: true
    include_sent_via_pipedream_flag: false
    thread_ts: "{{steps.trigger.event.event_ts}}"
    configureUnfurlSettings: true
    unfurl_links: true
    unfurl_media: true
- namespace: reply_to_a_message_other
  disabled: true
  runtime: nodejs20.x
  uses: slack_v2-reply-to-a-message@0.2.0
  props:
    text: "{{steps.code.$return_value.other}}"
    as_user: false
    addToChannel: true
    include_sent_via_pipedream_flag: false
    thread_ts: "{{steps.trigger.event.event_ts}}"
    unfurl_links: false
    unfurl_media: false
