schema: workflow/2022.04
name: Proof Ochestrator
settings:
  error_notification: true
  lambda_memory: 2048
  lambda_timeout: 240
  network: net_5Lnie3
triggers:
- id: hi_MWHpn8Z
steps:
- namespace: check_config
  runtime: nodejs20.x
  uses: "./check_config/entry.js"
  props:
    snowflake:
      authProvisionId: apn_yghdQYJ
- namespace: optional_delay
  runtime: nodejs20.x
  uses: "./optional_delay/entry.js"
- namespace: suspend_for_content_prep
  runtime: nodejs20.x
  uses: "./suspend_for_content_prep/entry.js"
  props:
    content_prep_url: https://eo6ad4e0u4fgvuo.m.pipedream.net
- namespace: utils_rebuild_braze_message
  runtime: nodejs20.x
  uses: "@mcclatchy/utils-rebuild-braze-message@0.0.7"
  props:
    braze:
      authProvisionId: apn_1Khpe1W
    app_id: 3f5340d5-1868-4fc0-b783-b36dd6185ab6
    scheduledItem: "{{steps.trigger.event.body}}"
    subject: "{{steps.trigger.event.body.name}}_{{steps.trigger.context.id}}"
- namespace: suspend_for_render
  runtime: nodejs20.x
  uses: "./suspend_for_render/entry.js"
  props:
    braze_render_url: https://eov0l2spkm1h5vp.m.pipedream.net
- namespace: suspend_for_screenshots
  runtime: nodejs20.x
  uses: "./suspend_for_screenshots/entry.js"
  props:
    email_test_api_url: https://eoihl6hmsymk4tc.m.pipedream.net
- namespace: extract_screenshots
  runtime: nodejs20.x
  uses: "./extract_screenshots/entry.js"
- namespace: upload_multiple_screenshots_to_drive
  runtime: nodejs20.x
  uses: "./upload_multiple_screenshots_to_drive/entry.js"
  props:
    google_drive:
      authProvisionId: apn_mnh5B9x
    screenshots: "{{steps.extract_screenshots.$return_value.screenshots}}"
    nextSendTime: "{{steps.trigger.event.body.next_send_time}}"
    messageName: "{{steps.trigger.event.body.name}}"
- namespace: filter
  runtime: nodejs20.x
  uses: "./filter/entry.js"
  props:
    _filter:
      continue: 'true'
      rules:
        t: and
        r:
        - a: "{{JSON.stringify(steps.trigger.event.body.tags)}}"
          op: str/
          b: Proof/Slack
        - a: "{{[0, 6].includes(new Date(steps.trigger.context.ts).getDay())}}"
          op: 'false'
          b: 'false'
- namespace: post_and_suspend
  disabled: true
  runtime: nodejs20.x
  uses: "./post_and_suspend/entry.js"
  props:
    dry_run: true
- namespace: apply_decision
  disabled: true
  runtime: nodejs20.x
  uses: "./apply_decision/entry.js"

